// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7aEN6-2b0Ssi3g_D7iCJJB9-hCAOueE8',
    appId: '1:388544385475:web:533e9e4cf6ed7177e7ad76',
    messagingSenderId: '388544385475',
    projectId: 'safar-5ceec',
    authDomain: 'safar-5ceec.firebaseapp.com',
    storageBucket: 'safar-5ceec.appspot.com',
    measurementId: 'G-GP3JSWGRFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU5Tq0bd22JdD4F9YVH50dUfZJ6TMR_wY',
    appId: '1:388544385475:android:1835a82face30461e7ad76',
    messagingSenderId: '388544385475',
    projectId: 'safar-5ceec',
    storageBucket: 'safar-5ceec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAngxm_cH36TkQBQ895DTyqGawnh-OccE',
    appId: '1:388544385475:ios:2b1b3840c97f9b41e7ad76',
    messagingSenderId: '388544385475',
    projectId: 'safar-5ceec',
    storageBucket: 'safar-5ceec.appspot.com',
    iosClientId: '388544385475-c0bdju8djs6ao33du0bor8un5fecnurh.apps.googleusercontent.com',
    iosBundleId: 'com.example.safarApp',
  );
}
